### ISSUE TITLE
Fix the mpris

### ISSUE THREAD

**Issue by soumyaDghosh** [CapeCrusader321/G4Music-Snap#1]
The mpris in this app is not working. Fix it, or I can try to fix it if you want, I'll share a PR. And don't copy code, you have already copied a lot. Don't register names before you have any real code in your hand. I have tried to make you understand this many times, and you at first made joke of me and then removed the comments, finding that the issue is real.

**Comment by CapeCrusader321** [comment]
Thanks for reporting this issue,i will try to fix that soon.

**Comment by CapeCrusader321** [comment]
Closing this as its Fixed, if it still persist, report this again.
